# Generated by Django 2.2 on 2019-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urlshorter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_short', models.CharField(max_length=20, unique=True)),
                ('url_long', models.URLField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
