# Generated by Django 2.2 on 2019-08-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsconverter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshorter',
            name='url_short',
            field=models.CharField(max_length=20),
        ),
    ]
