# Generated by Django 2.2 on 2019-08-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlsconverter', '0002_auto_20190831_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshorter',
            name='url_long',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
